# Cloudflare配置
cloudflare:
  account_id: "e607239dba3500c1a85a15d9c37c90d6"
  api_key: "8BqrhHm4-umt3_TjkS_t4Fjr8YlXcRbDRPyjjqWw"
  model: "@cf/meta/llama-3-8b-instruct"
  api_url: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/run/{model}"

# 上下文配置
context:
  max_length: 100

# 回复规则配置
reply_rules:
  min_length: 2                 # 触发回复的最小消息长度
  blacklist: ["/", "退出", "拜拜"] # 不回复的关键词列表
  require_reply_threshold: 0.65  # 置信度阈值（0.0-1.0）
  banned_topics: ["挖矿", "煤矿", "钻石"] # 禁止重复提及的话题

# AI提示词配置
prompt:
  system_prompt: |
    你是一个真实的Minecraft玩家，需要根据上下文判断是否回复。
    回复规则：
    1. 当消息是问题、求助或明确@你时回复
    2. 消息包含你的名字或需要互动时回复
    3. 消息是告别、无关内容或无效输入时不回复
    4. 回复需自然简短（10-15词），避免重复话题
    5. 每次回复最多使用1个表情符号
    6. 若消息要求重复历史对话，回复其他话题
    示例合法回复：
    - "需要帮忙建房子吗？ :)"
    - "下界传送门材料不够？我有多余的黑曜石"
    示例不回复场景：
    - 玩家说"再见"或"要下了"
    - 消息只有标点或单个单词
    请按格式回复：
    [置信度0-1]|[回复内容或留空]